config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get '/posts' => 'posts#index'


  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  get ':user_name', to: 'profiles#show', as: :profile
  post ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get '/posts/hashtag/:name', to:'posts#hashtags'

   resources :friendships do
    member do
      post 'approve_friend', to: 'friendships#approve_friend'
      post 'request_friend', to: 'friendships#request_friend'
      delete 'remove_friend', to: 'friendships#remove_friend'
      post 'block_friend', to: 'friendships#block_friend'
      post 'unblock_friend', to: 'friendships#unblock_friend'
      post 'common_friends', to: 'friendships#common_friends'
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      #flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

	

end 

app/views/profiles/edit.html.erb
<%= render 'posts/nav' %>

<br>
<br>
<br>

<div class="posts-wrap">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<%= render 'posts/nav' %>

<br>
<br>
<br>

<div class="posts-wrap">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name"><%= @user.user_name %></h3>
        <span> 
          <% if @user == current_user %>
            <%= button_to 'Edit Profile', edit_profile_path(@user.user_name),class: 'btn edit-button' %>
          <% elsif current_user.friend_with? @user %>Already Friends!
            <%= button_to "Delete!", remove_friend_friendship_path(id: @user.id), method: :delete, class: "btn btn-primary" %>
          <% elsif current_user.invited? @user %>Friend request sent!
            <%= button_to "Unsend!", remove_friend_friendship_path(id: @user.id), method: :delete, class: "btn btn-small btn-primary" %>
          <% elsif current_user.invited_by? @user %>
            <%= button_to "Accept!", approve_friend_friendship_path(id: @user.id), method: :post, class: "btn btn-small btn-primary" %>
            <%= button_to "Reject!", remove_friend_friendship_path(id: @user.id), method: :delete, class: "btn btn-small btn-primary" %>
          <% else %>
            <%= button_to "Request Friend", request_friend_friendship_path(id: @user.id),method: :post,class: "btn btn-primary" %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics text-center">
        <ul class="list-inline list-unstyled">
          <li>
            <strong><%= @user.posts.count %></strong>
            <%= "post".pluralize(@user.posts.count)%>
          </li>
          <li>
            <strong><%= @user.friends.count %></strong>
            <%= "follower".pluralize(@user.friends.count)%>
          </li>
          <li>
            <strong></strong>
            <%= "following" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= render 'posts/post', post: @post %>