config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get '/posts' => 'posts#index'


  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  get ':user_name', to: 'profiles#show', as: :profile
  post ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get '/posts/hashtag/:name', to:'posts#hashtags'

   resources :friendships do
    member do
      post 'approve_friend', to: 'friendships#approve_friend'
      post 'request_friend', to: 'friendships#request_friend'
      delete 'remove_friend', to: 'friendships#remove_friend'
      post 'block_friend', to: 'friendships#block_friend'
      post 'unblock_friend', to: 'friendships#unblock_friend'
      post 'common_friends', to: 'friendships#common_friends'
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.order('created_at DESC').page params[:page]

    respond_to do |format|
      format.js
      format.html
    end
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% if selector == "long" %>
  <li class="list-group-item">
    <ul class="list-inline list-unstyled text-center">
      <li class="notification-item">
        <% unless notification.read %>
          <span class="glyphicon glyphicon-asterisk"></span>
        <% end %>
      </li>
      <li class="notification-item">
        <%= link_to "#{notification.notified_by.user_name} left you a #{notification.notice_type}", link_through_path(notification) ,class: "nolink"%>&nbsp;<%= time_ago_in_words(notification.created_at) + " ago" %>
      </li>
    </ul>
  </li>
<% elsif selector == "short" %>
  <li>
    <%= link_to "#{notification.notified_by.user_name} left you a #{notification.notice_type}", link_through_path(notification), class: "nolink" %>
  </li>
<% end %>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle" type='button', id='dropdownMenu1', data-toggle='dropdown', aria-haspopup='true', aria-expanded='true'>
    <%= current_user.notifications.where(read:false).count %>
    <span class="glyphicon glyphicon-flag"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby='dropdownMenu1'>
    <li class="dropdown-header text-center">Notifications</li>
      <%= render current_user.notifications.where(read: false).last(5).reverse, selector: "short" %>
    </li>
    <li class="divider" role="separator">
      <li class="text-center">
        <%= link_to "View All", notifications_path %>
      </li>
    </li>
  </ul>
</div>

app/views/notifications/index.html.erb
<%= render '/posts/nav' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="notification-index-list list-group">
        <h1 class="text-center">Your Notifications</h1>
        <%= render @notifications, selector: "long" %>
      </ul>
    </div>
  </div>
</div>

<% if current_user.notifications.length > 10 %>
  <div id="paginator", class="text-center">
    <%= link_to_next_page @notifications, 'LOAD MORE', remote: true, id: 'load_more' %>
  </div>
<% end %>

app/views/notifications/index.js.erb
$('.notification-index-list').append("<%= escape_javascript(render @notifications, selector: "long") %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@notifications, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  