config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get '/posts' => 'posts#index'


  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  get ':user_name', to: 'profiles#show', as: :profile
  post ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get '/posts/hashtag/:name', to:'posts#hashtags'

   resources :friendships do
    member do
      post 'approve_friend', to: 'friendships#approve_friend'
      post 'request_friend', to: 'friendships#request_friend'
      delete 'remove_friend', to: 'friendships#remove_friend'
      post 'block_friend', to: 'friendships#block_friend'
      post 'unblock_friend', to: 'friendships#unblock_friend'
      post 'common_friends', to: 'friendships#common_friends'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_votable
  self.per_page = 10
  validates :user_id, presence: true
  belongs_to :user
  validates :image, presence: true
  has_many :notifications, dependent: :destroy  
  has_many :comments, dependent: :destroy
  validates :caption, length: { minimum: 3, maximum: 200 }
  is_impressionable

  has_and_belongs_to_many :tags

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg","audio/mp3"] }, :file_name => { :matches => [/mp3\Z/]}

  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.caption.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end 

  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear 
    hashtags = self.caption.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]
  impressionist actions: [:show,:index], unique: [:session_hash]

  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js { render 'posts/post_page' }
    end
  end

  def show
    impressionist(@post)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def like
  if @post.liked_by current_user
    create_notification @post
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def hashtags
    @tag = Tag.find_by(name: params[:name])
    @posts = @tag.posts
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption, :mp3)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      redirect_to root_path
    end
  end

  def create_notification(post)
    return if post.user == current_user
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: post.id,
                        notice_type: 'like')
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 5
    count_likers(votes)
  end

  def liked_post(post)
    if current_user.voted_for? post
      return link_to '', unlike_post_path(post.id), remote: true, id: "like_#{post.id}",
          class: "glyphicon glyphicon-heart btn-lg"
    else
      link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}",
          class: "like glyphicon glyphicon-heart-empty btn-lg"
    end
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        @u = voter.nick_name
        if voter.avatar.exists?
        user_names.push(link_to image_tag(voter.avatar.url(:thumb),title:@u,:class=> "img-circular-like"),
                                profile_path(voter.user_name),
                                class: 'user-img-likes img-circle')
        else
          user_names.push(link_to image_tag('defaultavatar.png',title:@u,:class=> "img-circular-like"),
                                  profile_path(voter.user_name),
                                  class: 'user-img-likes img-circle')
        end
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end

  def render_with_hashtags(caption)
    caption.gsub(/#\w+/){|word| link_to word, "/posts/hashtag/#{word.downcase.delete('#')}",{:class=>"nolink",:style=>'color:#1a84a5'}}.html_safe 
  end
end

app/views/posts/_form.html.erb
<div class="posts-wrap">
  <div class="post">
    <div class="post-body">
      <%= form_image_select(@post) %>
      <div class="image-wrap">
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
              <h4>Upload an mp3/song:</h4>
              <center><%= f.file_field :mp3 %></center>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <%= display_likes post %>
</div>

app/views/posts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="font-size: 25px;">Mnimi</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><%= render 'notifications/notification_dropdown' %></li>
        <li><%= link_to "Feed",posts_path%></li>
        <li><%= link_to "New Post",new_post_path%></li>
        <li><%= link_to "My Posts",'#'%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/<%= current_user.user_name %>">Profile</a></li>
            <li><%= link_to('Edit Profile/Settings',edit_user_registration_path) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/_post.html.erb
<div class="container">
<% @posts.each_slice(2) do |posts| %>
<div class="posts-wrapper row">
  <% posts.each do |post| %>
<div class="col-lg-4 col-md-offset-1">
    <div class="post">
      <div class="post-head">
        <div class="thumb-img"></div>
        <div class="user-name">
          <%= link_to post.user.user_name, profile_path(post.user.user_name), class:"nolink"%>
        </div>
        <div class="time-ago">
          <%= time_ago_in_words post.created_at %> ago
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <div class="post-bottom">
        <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div class="caption-content">
        <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name), class:"nolink"%>
        </div>
        <%= render_with_hashtags(post.caption) %>
        </div>
              <% if post.mp3.exists? %>
        <div id="waveform">
        <div class="text-center">
          <div class="controls">
<button class="btn" onclick="wavesurfer.on('ready', wavesurfer.play.bind(wavesurfer)); wavesurfer.load('<%= post.mp3.url %>');"> Play</button>
</div>
  </div>
      </div>
      <% end %>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments.any? %>
            <div class="paginator" id="#comments-paginator-<%= post.id %>">
              <% unless post.comments.count <= 4 %>
                <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
              <% end %>
            </div>
            <%= render post.comments.last(4), post: post %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-like-form">
      <div class="row col-sm-4 like-button">
    <%= liked_post post %>
  </div>
  <div class="row comment-form col-sm-10">
    <br>
    <%= form_for([post, post.comments.build], remote:true) do |f| %>
      <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}", :style => "background: none;
  border: none;" %>
    <% end %>
  </div>
</div>
  

    </div><%# post %>
    </div><%# offset %>
  <% end %> <%# each post %>
</div><%# post-wrapper row %>
<% end %> <%# slice %>
</div><%# container %>

<script>
  var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'orange',
    progressColor: 'black',
    barWidth: '1'
});
</script>

app/views/posts/_postsh.html.erb
<div class="posts-wrap">
  <%= link_to :back, class:"nolink" do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
  <% end %>
  <br>
  <br>
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to @post.user.user_name, profile_path(@post.user.user_name), class:"nolink" %>
      </div>
      <div class="time-ago">
  <%= time_ago_in_words @post.created_at %> ago
</div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium), class:'img-responsive'%>
    </div>
    <div class="post-bottom">
      <%= render 'posts/likes', post: @post %>
      <div class="caption">
      <% if @post.user_id == current_user.id %>
      <br>
        <%= "#{@post.impressionist_count(:filter=>:ip_address)} views so far!" %>
      <% end %>
      <br><br>
      <div class="caption-content">
        <div class="user-name">
          <%= link_to @post.user.user_name, profile_path(@post.user.user_name), class:"nolink" %>
        </div>
        <%= render_with_hashtags(@post.caption) %>
      </div>
      <% if @post.mp3.exists? %>
      <div id="waveform">
      </div>
      <% end %>
      <div class="comments" id="comments_<%= @post.id %>">
      <% if @post.comments.any? %>
        <div class="paginator" id="#comments-paginator-<%= @post.id %>">
          <% unless @post.comments.count <= 4 %>
            <%= link_to "view all #{@post.comments.count} comments", post_comments_path(@post), remote: true, class: 'more-comments', data: {post_id: "#{@post.id}", type: "html"} %>
            <% end %>
          </div>
          <%= render @post.comments.last(4), post: @post %>
      <% end %>
    </div>
    </div>
    </div>
    <div class="comment-like-form-c row">
      <div class="col-sm-2 like-button row">
      <%= liked_post @post %>
    </div>
      <div class="row comment-form col-sm-11 row">
      <br>
        <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{@post.id}", :style => "background: none;
  border: none;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'black',
    progressColor: 'red',
    barWidth: '1'
});

  wavesurfer.load("<%= @post.mp3.url %>");
  wavesurfer.on('ready', wavesurfer.play.bind(wavesurfer));
</script>

app/views/posts/edit.html.erb
<%= render 'nav' %>
<br>
<br>
<br>
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } , class:"nolink"%>
  |
  <%= link_to "Cancel", posts_path , class:"nolink"%>
</div>

app/views/posts/hashtags.html.erb
<%= render 'nav' %>
<br>
<br>
<br>
<h1><center> Search for '#<%= @tag.name %>' </center></h1>
<h3><center> <%= pluralize(@posts.size,"post") %>  </center></h3>
<div class="posts-wrap">
<% @posts.each do |post| %>
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name), class:"nolink" %>
      </div>
      <div class="time-ago">
  <%= time_ago_in_words post.created_at %> ago
</div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <%= render 'posts/likes', post: post %>
      <br>
      <div class="caption">
      <div class="caption-content">
        <div class="user-name">
          <%= link_to post.user.user_name, profile_path(post.user.user_name), class:"nolink" %>
        </div>
        <%= render_with_hashtags(post.caption) %>
      </div>
      <% if post.mp3.exists? %>
      <div id="waveform">
      </div>
      <% end %>
      <div class="comments" id="comments_<%= post.id %>">
      <% if post.comments.any? %>
        <div class="paginator" id="#comments-paginator-<%= post.id %>">
          <% unless post.comments.count <= 4 %>
            <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
            <% end %>
          </div>
          <%= render post.comments.last(4), post: post %>
      <% end %>
    </div>
    </div>
    </div>
    <div class="comment-like-form-c row">
      <div class="col-sm-2 like-button row">
      <%= liked_post post %>
    </div>
      <div class="row comment-form col-sm-11 row">
      <br>
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}", :style => "background: none;
  border: none;" %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'nav' %>
<br>
<br>
<br>

<div id="feed"><%# here %>
<%= render 'post' %> <%# here render 'post' %>
</div><%# here %>


<div class="hide-wp">
<div id="infinite-scrolling">
<%= will_paginate @posts %><%# here %>
</div>
<% if @posts.current_page == @posts.total_pages%>
<p>YOU HAVE HIT ROCK BOTTOM!</p>
<% end %>
</div>

<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'SHOW MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.js.erb
$('#feed').append("<%= escape_javascript(render 'post')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/unlike');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<%= render 'nav' %>
<br>
<div class="posts-wra">
<%= render 'form' %>
</div>

<style>
.posts-wra {
  padding-top: 40px;
  margin: 0 auto;
  max-width: 465px;
  width: 100%;
}
</style>

app/views/posts/post_page.js.erb
$('#feed').append('<%= j render 'post' %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/show.html.erb
<%= render 'nav' %>
<br>
<br>
<br>
<%= render 'postsh' %>

<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path , class:"nolink"%>
    |
    <%= link_to "Edit Post", edit_post_path(@post), class:"nolink" %>
  </div>
<% end %>

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");